definition = {
    'backdated_time': {},
    'backdated_time_granularity': {},
    'comments': {'edge_type': 'comment'},
    'cover_photo': {},
    'created_time': {'default': True},
    'description': {'default': True},
    'event': {'edge_type': 'event'},
    'from': {},
    'link': {},
    'location': {},
    'modified_major': {},
    'name': {'default': True},
    'place': {},
    'photo_count': {'default': True},
    'photos': {'edge_type': 'photo'},
    'updated_time': {'default': True},
    'type': {},
    'video_count': {'default': True},
    # 'likes': '',
    # 'reactions': '',
    # 'comments': ''
}
