definition = {
    'fields': {
        'backdated_time': {},
        'backdated_time_granularity': {},
        'can_backdate': {'omit': True},
        'can_upload': {'omit': True},
        'comments': {'edge_type': 'comment'},
        'count': {},
        'cover_photo': {},
        'created_time': {'default': True},
        'description': {'default': True},
        'edit_link': {'omit': True},
        'event': {'edge_type': 'event'},
        'from': {},
        'is_user_facing': {'omit': True},
        'likes': {},
        'link': {},
        'location': {},
        'modified_major': {},
        'name': {'default': True},
        'photo_count': {'default': True},
        'photos': {'edge_type': 'photo'},
        'picture': {},
        'place': {},
        'privacy': {},
        'reactions': {},
        'sharedposts': {'omit': True},
        'type': {},
        'updated_time': {'default': True},
        'video_count': {'default': True},
    }
}
