definition = {
    'attending_count': {},
    'category': {},
    'comments': {'edge_type': 'comment'},
    'cover': {},
    'declined_count': {},
    'description': {'default': True},
    'end_time': {'default': True},
    'event_times': {'default': True},
    'feed': {'edge_type': 'post'},
    'interested_count': {},
    'is_canceled': {},
    'maybe_count': {},
    'name': {'default': True},
    'noreply_count': {},
    'owner': {},
    'photos': {'edge_type': 'photo'},
    'picture': {'edge_type': 'photo'},
    'place': {},
    'start_time': {'default': True},
    'timezone': {},
    'type': {},
    'updated_time': {}
}
