definition = {
    'fields': {
        'admins': {'omit': True},
        'attending': {'omit': True},
        'attending_count': {},
        'can_guests_invite': {'omit': True},
        'can_viewer_post': {'omit': True},
        'category': {},
        'comments': {'edge_type': 'comment'},
        'cover': {},
        'declined': {'omit': True},
        'declined_count': {},
        'description': {'default': True},
        'end_time': {'default': True},
        'event_times': {'default': True},
        'feed': {'edge_type': 'post'},
        'guest_list_enabled': {'omit': True},
        'interested': {'omit': True},
        'interested_count': {},
        'is_canceled': {},
        'is_draft': {'omit': True},
        'is_page_owned': {'omit': True},
        'is_viewer_admin': {'omit': True},
        # Added field
        'live_videos': {'omit': True},
        'maybe': {'omit': True},
        'maybe_count': {},
        'name': {'default': True},
        'noreply': {'omit': True},
        'noreply_count': {},
        'owner': {},
        'parent_group': {'omit': True},
        'photos': {'edge_type': 'photo'},
        'picture': {},
        'place': {},
        'posts': {'omit': True},
        'roles': {'omit': True},
        'scheduled_publish_time': {'omit': True},
        'start_time': {'default': True},
        'ticket_uri': {'omit': True},
        'ticketing_privacy_uri': {'omit': True},
        'ticketing_terms_uri': {'omit': True},
        'timezone': {},
        'type': {},
        'updated_time': {},
        'videos': {'omit': True},
    }
}
