definition = {
    'node_batch_size': 5,
    'fields': {
        'ad_break_config': {'omit': True},
        'ad_break_failure_reason': {'omit': True},
        'blocked_users': {'omit': True},
        'broadcast_start_time': {},
        'comments': {'edge_type': 'comment'},
        'copyright': {'omit': True},
        'creation_time': {'default': True},
        'dash_preview_url': {'omit': True},
        'description': {'default': True},
        'embed_html': {},
        'errors': {'omit': True},
        'from': {},
        'is_manual_mode': {'omit': True},
        'is_reference_only': {'omit': True},
        'likes': {},
        'live_encoders': {'omit': True},
        'live_views': {},
        'permalink_url': {'default': True},
        'planned_start_time': {},
        'reactions': {},
        'seconds_left': {'omit': True},
        'secure_stream_url': {},
        'status': {},
        'stream_url': {},
        'title': {'default': True},
        'video': {'edge_type': 'video'},
    }
}
