definition = {
    'about': {'default': True},
    'affiliation': {},
    'albums': {'edge_type': 'album'},
    'best_page': {},
    'bio': {},
    'birthday': {},
    'category': {'default': True},
    'category_list': {},
    'checkins': {},
    'contact_address': {},
    'cover': {},
    'current_location': {},
    'description': {},
    'display_subtext': {},
    'emails': {},
    'engagement': {},
    'events': {'edge_type': 'event'},
    'fan_count': {},
    'featured_video': {'edge_type': 'video'},
    'general_info': {},
    'hometown': {},
    'is_verified': {},
    'link': {'default': True},
    'likes': {'edge_type': 'page', 'follow_edge': False},
    'location': {},
    'name': {'default': True},
    'overall_star_rating': {},
    'rating_count': {},
    'parent_page': {'edge_type': 'page', 'follow_edge': False},
    'personal_info': {},
    'personal_interests': {},
    'phone': {},
    'screennames': {},
    'single_line_address': {},
    'talking_about_count': {},
    'username': {'default': True},
    'verification_status': {},
    'website': {'default': True},
    'whatsapp_number': {}
    # 'feed': '',
    # 'milestones': '',
    # 'picture': '',
    # 'posts': '',
    # 'video_lists': '',
    # 'videos': '',
    # 'visitor_posts': ''
}