definition = {
    'caption': {},
    'comments': {'edge_type': 'comment'},
    'created_time': {'default': True},
    'description': {},
    'from': {'default': True},
    'icon': {},
    'likes': {},
    'link': {},
    'message': {'default': True},
    'message_tags': {},
    'object_id': {},
    'parent_id': {},
    'permalink_url': {'default': True},
    'picture': {},
    'place': {},
    'properties': {},
    'reactions': {},
    'shares': {},
    'source': {},
    'status_type': {'default': True},
    'story': {},
    'to': {'default': True},
    'type': {'default': True},
    'updated_time': {'default': True}
}
