definition = {
    'node_batch_size': 50,
    'fields': {
        'actions': {'omit': True},
        'admin_creator': {'omit': True},
        'allowed_advertising_objectives': {'omit': True},
        'application': {'omit': True},
        'attachments': {'omit': True},
        'backdated_time': {'omit': True},
        'call_to_action': {'omit': True},
        'caption': {},
        'child_attachments': {'omit': True},
        'comments': {'edge_type': 'comment'},
        'comments_mirroring_domain': {'omit': True},
        'coordinates': {'omit': True},
        'created_time': {'default': True},
        'description': {},
        'dynamic_posts': {'omit': True},
        'event': {'edge_type': 'event', 'follow_edge': False},
        'expanded_height': {'omit': True},
        'expanded_width': {'omit': True},
        'feed_targeting': {'omit': True},
        'from': {'default': True},
        'full_picture': {},
        'height': {'omit': True},
        'icon': {},
        'insights': {'omit': True},
        'instagram_eligibility': {'omit': True},
        'is_app_share': {'omit': True},
        'is_expired': {'omit': True},
        'is_hidden': {'omit': True},
        'is_instagram_eligible': {'omit': True},
        'is_popular': {'omit': True},
        'is_published': {'omit': True},
        'is_spherical': {'omit': True},
        'likes': {},
        'link': {'default': True},
        'message': {'default': True},
        'message_tags': {},
        'multi_share_end_card': {'omit': True},
        'multi_share_optimized': {'omit': True},
        'name': {},
        'object_id': {},
        'parent_id': {},
        'permalink_url': {'default': True},
        'picture': {},
        'place': {},
        'privacy': {'omit': True},
        'promotion_status': {'omit': True},
        'properties': {},
        'reactions': {},
        'scheduled_publish_time': {'omit': True},
        'seen': {'omit': True},
        'sharedposts': {'omit': True},
        'shares': {},
        'source': {},
        'sponsor_tags': {'omit': True},
        'status_type': {'default': True},
        'story': {},
        'story_tags': {'omit': True},
        'subscribed': {'omit': True},
        'target': {'omit': True},
        'targeting': {'omit': True},
        'timeline_visibility': {'omit': True},
        'to': {'default': True},
        'type': {'default': True},
        'updated_time': {'default': True},
        'via': {},
        'video_buying_eligibility': {'omit': True},
        'width': {'omit': True},
        'with_tags': {'omit': True},
    }
}
