definition = {
    'backdated_time': {},
    'backdated_time_granularity': {},
    'comments': {'edge_type': 'comment'},
    'content_tags': {},
    'created_time': {'default': True},
    'description': {'default': True},
    'embed_html': {},
    'embeddable': {},
    'event': {'edge_type': 'event', 'follow_edge': False},
    'format': {},
    'from': {},
    'icon': {},
    'length': {},
    'live_status': {},
    'permalink_url': {'default': True},
    'picture': {},
    'place': {},
    'privacy': {},
    'published': {},
    'source': {},
    'status': {},
    'title': {'default': True},
    'universal_video_id': {},
    'updated_time': {'default': True},
    # 'likes': '',
    # 'reactions': '',
}
