definition = {
    'ad_breaks': {'omit': True},
    'auto_generated_captions': {'omit': True},
    'backdated_time': {},
    'backdated_time_granularity': {},
    'captions': {'omit': True},
    'comments': {'edge_type': 'comment'},
    'content_category': {},
    'content_tags': {},
    'created_time': {'default': True},
    'custom_labels': {'omit': True},
    'description': {'default': True},
    'embed_html': {},
    'embeddable': {},
    'event': {'edge_type': 'event', 'follow_edge': False},
    'format': {},
    'from': {},
    'icon': {},
    'is_crosspost_video': {'omit': True},
    'is_crossposting_eligible': {'omit': True},
    'is_instagram_eligible': {'omit': True},
    'is_reference_only': {'omit': True},
    'length': {},
    'likes': {},
    'live_status': {},
    'monetization_status': {'omit': True},
    'permalink_url': {'default': True},
    'picture': {},
    'place': {},
    'privacy': {},
    'published': {},
    'reactions': {},
    'scheduled_publish_time': {'omit': True},
    'sharedposts': {'omit': True},
    'source': {},
    'sponsor_tags': {'omit': True},
    'status': {},
    'tags': {'omit': True},
    'thumbnails': {'omit': True},
    'title': {'default': True},
    'universal_video_id': {},
    'updated_time': {'default': True},
    'video_insights': {'omit': True},
}
